services:
  beszel:
    image: henrygd/beszel
    container_name: beszel
    restart: unless-stopped
    volumes:
      - ./beszel_data:/beszel_data
      - ./beszel_socket:/beszel_socket
    ports:
      - 127.0.0.1:8090:8090
    networks:
      - homelab
    labels:
      - homepage.group=Observability
      - homepage.name=Beszel
      - homepage.icon=beszel.png
      - homepage.href=https://${TAILSCALE_MACHINE}.${TAILSCALE_TAILNET}:8090
      - homepage.description=Server monitoring platform
      - homepage.widget.type=beszel
      - homepage.widget.url=http://beszel:8090
      - homepage.widget.username=${USERNAME}
      - homepage.widget.password=${PASSWORD}
      - homepage.widget.systemId=homelab
      - homepage.widget.version=2

  beszel-agent:
    image: henrygd/beszel-agent
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    environment:
      LISTEN: /beszel_socket/beszel.sock
      HUB_URL: http://localhost:8090
      KEY: ${KEY}
      TOKEN: ${TOKEN}
    volumes:
      - ./beszel_agent_data:/var/lib/beszel-agent
      - ./beszel_socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/hdd/.beszel:/extra-filesystems/hdd:ro

networks:
  homelab:
    name: homelab
    external: true
